#! /bin/sh

sxhkd &
kitty &
$HOME/.config/polybar/launch.sh &
$HOME/.config/.screenlayout/display.sh

exec bspwm

#### MONITORS ####

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='V' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a google-chrome desktop='^2'
bspc rule -a code desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
