#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
kitty &
$HOME/.config/polybar/launch.sh
#$HOME/Downloads/scripts/xrandr.sh &
nitrogen --restore
picom

super + shift + {1-9,0}
bspc monitor -d 1 2 3 4

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome-stable desktop='^2'
bspc rule -a code desktop='^3'
bspc rule -a spotify desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
