#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
setxkbmap -option grp:alt_shift_toggle us,ru &
xrandr -s 1920x1080
$HOME/.config/polybar/launch.sh --forest

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=of
bspc rule -a telegram-desktop desktop='^3' follow=on

#set your wallpaper upon logging in &

feh --bg-fill $HOME/Pictures/wall-1920x1080.jpg &

#This invokes pywal with your image simply replace the path

wal -i $HOME/Pictures/wall-1920x1080.jpg 

bspc config normal_border_color "$color1"

bspc config active_border_color "$color2"

bspc config focused_border_color "$color15"

#Use the line below if you are on bspwm >= 0.9.4

bspc config presel_feedback_color "$color1"

#place the focus on where the mouse is; if you like clicking windows to focus, comment this line

bspc config focus_follows_pointer true

#Define window settings

bspc config border_width 2

bspc config window_gap 12

bspc config split_ratio 0.52

bspc config borderless_monocle true

bspc config gapless_monocle true
